#
# Plugin by fergydanny (https://sysadamant.com)
#

#
# General
#
global:
  # Set how spawners look. Available placeholder: %mob% => mob name
  display:
    name: '&e%mob% &fSpawner'
    lore:
      - '&aPlace this down for'
      - '&a %mob% Spawner.'
    lore-enabled: true

#
# /mineablespawners command
#
main:
  # The help message will only show the commands a player has access to.
  help-message:
    title: '&eMineableSpawners:'
    give: '&c/mineablespawners give <player> <type> <amount> &7(Give a player a spawner)'
    set: '&f/mineablespawners set <type> &7(Set the type of the spawner you are looking at)'
    types: '&7/mineablespawners types'

#
# /mineablespawners give command
#
give:
  # Whether or not to require the permisison "mineablespawners.give" to give spawners.
  require-permission: true
  messages:
    no-permission: '&cNo Permission.'
    player-does-not-exist: '&cThat player does not exist.'
    invalid-type: '&cThat type does not exist. Use &7/mineablespawners types &cto list all available types.'
    invalid-amount: '&cThe amount you entered is invalid. Please try again.'
    inventory-full: '&cThe targets inventory is full. No spawner has been given.'
    # Here you can use the placeholders: %amount% => amount given, %mob% => mob name, %target% => player receiving spawners
    success: '&aYou have successfully given %amount%x %mob% Spawners to %target%!'
    received: '&aYou have received %amount%x %mob% Spawners!'

#
# /mineablespawners set command
#
set:
  # Whether or not to require the permisison "mineablespawners.set" to give set spawner type while looking at it.
  require-permission: true
  messages:
    no-permission: '&cNo Permission.'