name: MineableSpawners
version: 1.4
main: net.momentonetwork.MineableSpawners
authors: [fergydanny]
description: A simplistic silk spawner plugin
website: https://momentonetwork.net
api-version: 1.13
commands:
  spawner: Change a spawner''s type.
  spawnergive: Give a player a spawner.
